inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature']

Documentation:
  Enabled: false