default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:

development:
  <<: *default
  database: edools_development

test:
  <<: *default
  database: edools_test

# production:
#   <<: *default
#   database: edools_production
#   username: edools
#   password: <%= ENV['EDOOLS_DATABASE_PASSWORD'] %>
