# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfb5257bbfd9b6014e381b9e55488799f9a4171f842b6c6849f68f420181e0bddeed53f3ac36aa9caa1d34bcdbb7bc16530ab126a45121f789c3304fd7d1071f

test:
  secret_key_base: 8e853880d60b9be1b23cd7450874d71ec150457e96f73293e8aadbecfb614083429f8f1af0abf86dfef31e6839ad48c34b933c01d51c2b94f35f8022dcb80e0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
