# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67670dbd6ff7c4bf051a535ac312145504de677a153025681eb86b3147d12de28f200ac4bcdce786890406abf84df29afd8f1462683b48bf3d88b8c8d1b84f8b

test:
  secret_key_base: 7170feeea98d047852e6355c71841eecccf8cd19f3ce43cee7c019e508e9f92fb8ddcbad63a8c8d81fb6c6dbbc1ea8579e224a14cb7ddbdf0e85657c800c87db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
