# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e1110f9a9d92662a8226c62a7d365546d9dbe9b36eb90c9870a1d24d57960c301b306b0e971d76a993d8c6508d4705f8fe52c7cfaeba22075ba5966e6822763

test:
  secret_key_base: c134a36f1096338f9b3ca3e4e17175155bb71fdd27ce0d2fd67fb3063c225fdc5a405e7cf351e8061062d520f50f97d1fe4ccbde4e48e5cd993beb947e6a1370

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
